on: [push, pull_request]
name: With DateTime::Format::ISO8601

jobs:
  build:
    runs-on: 'macos-12'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1
      - name: Test and build
        run: |
          cpanm --installdeps .
          cpanm DateTime::Format::ISO8601
          perl Makefile.PL
          make test
